version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
    commands:
      # Install AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install


  pre_build:
    commands:
      # Install dependencies
      npm install  
      # Authenticate with ECR 
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 844349971621.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      npm run build
      
      # build image
      docker build -t helios_nestjs:latest .
      
      #push to ECR Container Registry
      docker tag helios_nestjs:latest 844349971621.dkr.ecr.eu-north-1.amazonaws.com/helios_nestjs:latest

  post_build:
    commands:
      # Push the Docker image to the ECR repository
      docker push 844349971621.dkr.ecr.eu-north-1.amazonaws.com/helios_nestjs:latest
      
      # Create a new task definition
      aws ecs register-task-definition --family helios-backend-task-definition --container-definitions '[
      {
      "name": "helios_nestjs",
      "image": "844349971621.dkr.ecr.eu-north-1.amazonaws.com/helios_nestjs:latest",
      "portMappings": [
        {
          "containerPort": 3000,
          "protocol": "tcp"
        }
      ]
    }
    ]'

  deploy:
    commands:
      # Update the ECS service
      aws ecs update-service --cluster backend --service helios-ec2-backend-service --force-new-deployment
